update

diff --git a/lab3/generator_v b/lab3/generator_v
--- a/lab3/generator_v
+++ b/lab3/generator_v
@@ -8,8 +8,8 @@ while true; do
 		then 
 		break
 	fi
-	if ! [[ $LINE =~ $re ]] ; then
-   		echo "error: Not a number";
-   		break;
+	if ! [[ $LINE =~ $re ||  $LINE == "+" || "$LINE" == "*" ]] ; then
+		rm pipe
+   		echo "error: Not a number"; exit 1
 	fi
 done
